### ISSUE TITLE
Quite slow compared to original 

### ISSUE THREAD

**Issue by Binero** [TLmaK0/rustneat#17]
This library takes around 200 generations to solve XOR and it usually takes around several minutes, yet according to the research papers NEAT should be able to solve XOR in around 30 generations. 

Is there a particular reason for this deficiency?

**Comment by TLmaK0** [comment]
with `cargo test --release` it takes only a few seconds on my AMD Quad Core. Anyway rustneat is very alpha, there are a lot of things to review to make sure it implements NEAT correctly. Rustneat also starts with 1 neuron without connections, and other implementations starts with at least one pair of neurons for every sensor (if I remember correctly) Try other parameters inside the code to get better values. If you found better performance please post here!

The code is very easy to understand, any help will be appreciated.
